# Generated by Django 3.2.7 on 2021-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_forum_query_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_query',
            name='query_id',
            field=models.TextField(default='0000000000'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.TextField(default='0000000000'),
        ),
    ]
