# Generated by Django 3.2.5 on 2021-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferti_forms', '0002_remove_fertilizerdata_cropname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerdata',
            name='crop',
            field=models.CharField(default='rice', max_length=30),
        ),
    ]
